import json
import asyncio
import re
from google.adk.agents import Agent
from google.adk.models.base_llm import BaseLlm
from src.rule_onboarding.utils.logger import setup_logger

#--- LOGGER SETUP ---
logger = setup_logger("DQ_FINE_TUNED_RULE_EXTRACTION_AGENT")

class LocalGemmaModel(BaseLlm):

    async def generate_content_async(self, messages, **kwargs):
            """Extracts text from GenerateContentRequest object structure."""
            instruction = ""
            try:
                # Access the 'contents' attribute of the ADK Request object
                if hasattr(messages, 'contents') and len(messages.contents) > 0:
                    # The 'contents' is a list of Content objects. Get the last one.
                    last_content = messages.contents[-1]
                    
                    # Each Content object has a 'parts' list
                    if hasattr(last_content, 'parts') and len(last_content.parts) > 0:
                        # The 'Part' object contains the 'text' attribute
                        instruction = last_content.parts[0].text
                    else:
                        instruction = str(last_content)
                else:
                    # Fallback: try to extract text using regex if structure is unexpected
                    match = re.search(r"text='(.*?)'", str(messages))
                    if match:
                        instruction = match.group(1)
                    else:
                        instruction = str(messages)

            except Exception as e:
                logger.error(f"Extraction failed: {e}")
                instruction = str(messages)

            # Final cleanup to remove any remaining 'Part' or 'text' artifacts
            if "text='" in instruction:
                instruction = instruction.split("text='")[-1].split("'")[0]

            logger.info(f"The instruction that is going for the fine tuned model is : {instruction}")

            # Pass ONLY the string to the wrapper
            from src.rule_onboarding.finetune.wrapper import rule_extraction_model_wrapper
            
            response_dict = await asyncio.to_thread(
                rule_extraction_model_wrapper.generate, 
                instruction
            )
            logger.info(f"Local Gemma Class: Completed Async Inference.")
            logger.info(f"Received Response Dict: {response_dict}")
            
            # This is the JSON string generated by the fine-tuned model
            response_json_str = json.dumps(response_dict)
            
            # Standard MockResponse for ADK Telemetry
            class MockUsage:
                prompt_token_count = 0
                candidates_token_count = 0
                total_token_count = 0
                
            # The 'Part' object that holds the text
            class MockPart:
                def __init__(self, text):
                    self.text = text

            # The 'Content' object that holds the parts list
            class MockContent:
                def __init__(self, text):
                    # This fixes the 'AttributeError: str object has no attribute parts'
                    self.parts = [MockPart(text)]
                
                # Fallback for code that tries to treat content as a string
                def __str__(self):
                    return self.parts[0].text
                
            class MockResponse:
                def __init__(self, text):
                    self.text = text
                    self.content = MockContent(text)
                    self.usage_metadata = MockUsage()
                    self.finish_reason = "STOP"
                    self.partial = False
                    self.candidates = [self]
                    
                def model_dump(self, **kwargs):
                    """Mimics Pydantic's model_dump for ADK telemetry."""
                    return {
                        "content": self.content,
                        "finish_reason": self.finish_reason,
                        "partial": self.partial,
                        "usage_metadata": {
                            "prompt_token_count": 0,
                            "candidates_token_count": 0,
                            "total_token_count": 0
                        }
                    }
                
                def __str__(self): 
                    return self.text

            yield MockResponse(response_json_str)

# Initialize with the required 'model' field
custom_local_model = LocalGemmaModel(model="gemma-2-2b-it-fine-tuned")

SYSTEM_INSTRUCTION = """
You are a Data Quality Extraction Assistant. 
Convert the user's natural language request into the fine-tuned DQ Rule JSON schema.
"""

fine_tune_rule_extraction_agent = Agent(
    name="fine_tune_rule_extraction_agent",
    model=custom_local_model,
    instruction=f"{SYSTEM_INSTRUCTION}\n",
    output_key="raw_rule_details"
)